name: CI - Unit & Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
      GEONAMES_USERNAME: ${{ secrets.GEONAMES_API_KEY }}

    steps:
      #  Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      #  Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      #  Install dependencies
      - name: Install dependencies
        run: npm ci

      #  Run all tests
      - name: Run unit + integration tests
        run: npm run test
